### ISSUE TITLE
Add administration instructions

### ISSUE THREAD

**Issue by msfeldstein** [stellar/django-polaris#103]
When running locally via docker its unclear how to enter the admin panel, ie what the url is, what the credentials are.  its also unclear how to run the [bash commands](https://github.com/stellar/django-polaris#python-code-and-bash-commands).  Instead of running `python manage.py shell` i had to run `docker exec -it 5448007c7098 pipenv run python manage.py shell`  it should be easier to do this kind of thing

**Comment by JakeUrban** [comment]
At the time this issue was filed, the local deployment of Polaris didn't include an `/admin` endpoint, but it does now. 

However, there is no admin user created right now. This is tricky to do with our current setup and relates to #108 (db.sqlite3 in git) since there needs to be a database file on the host in order for the data to persist when docker containers are destroyed. I'll get to fixing this in the next sprint.

Regarding the bash commands, you would no longer need the `pipenv run` part, so it would just be
```
docker exec -it <container id> python manage.py shell
```
If you're running the local development server via docker-compose there's no way to not have need the `docker exec -it <container id>` prefix. 

The reason its not documented like that in the README is because some users of Polaris will be contribution to the repo (in which case they would use docker-compose) but most (I assume) will be installing Polaris in their local environment via `pip install django-polaris` (in which case you wouldn't use `docker exec ...` prefix).
