### ISSUE TITLE
SEP-6 Link created Transaction object in process_sep6_request()

### ISSUE THREAD

**Issue by yuriescl** [stellar/django-polaris#247]
In SEP-6 there can be custom fields defined by the Anchor:
```
GET /info

{
  "deposit": {
    ...
    "fields": {
      "email_address": {
        "description": "Beneficiary email address",
        "optional": False,
      },
      "wallet_name": {
        "description": "Wallet name",
        "optional": True,
      },
    }
  }
}
```

When SEP-6 `/deposit` or `/withdraw` is called, to handle the validation, I imagine I'd have to implement and register the function `DepositIntegration.process_sep6_request`.
Besides validating the values, I'd like to save them and associate them with the Transaction created in SEP-6, maybe using a new model `TransactionExtra` and having a `ForeignKey` pointing to the SEP-6  `Transaction`.

My issue is that Polaris creates the Transaction after calling `process_sep6_request`, so there's no way for me to create a `TransactionExtra` because there would not be a `Transaction` to point to yet.
I'd like to know if there's any recommendation regarding saving the values of these fields and associating them with the `Transaction`.

**Comment by JakeUrban** [comment]
The reason `Transaction` is not created before the call to `process_sep6_request` is because the function could return a 403 response, in which case Polaris shouldn't create a Transaction.

However, this obviously is inconvenient for developers using Polaris. The same problem arose while implementing SEP-31 support, so I added a `transaction_id` parameter to `process_send_request` (the SEP-31 equivalent of `process_sep6_request`). 

The `Transaction` record in the DB still doesn't exist when `process_send_request` is called, but it still allows the developer to save the ID and use it to connect the transaction to other tables. This is better but still not ideal.

We're going to release 1.0 soon and are currently making some breaking changes to the API. One change we could make is to pass a `Transaction` object to `process_sep6_request` and `process_send_request`, and allow the developer to save the `Transaction` object to the DB if they plan to return a success response.

Another solution could be adding post-transaction-creation integration functions to the respective SEP-6 and SEP-31 endpoints. This would allow you to use the transaction after its saved to the DB. I'll file an issue for this discussion.

While I work on a new release with one of the above solutions ^, I can think of a solution, although not ideal. Have you heard of [Django Signals](https://docs.djangoproject.com/en/2.2/topics/signals/)? You can register a django signal function for the `Transaction` `post_save` event and connect it to the rest of your data model if the transaction was just created.

**Comment by yuriescl** [comment]
Using the `post_save` signal would not be sufficient, since the signal would provide only the `Transaction` instance without the SEP-6 parameters linked to it.
The post-transaction-creation integration functions would be a better solution, since it could provide both the parameters and the `Transaction` instance created.
@JakeUrban Is there any estimation on when v1.0 will be released, possibly with the post-

**Comment by JakeUrban** [comment]
No estimation, but its really about just getting the things that need to be changed done. You can see from the issues filed that there aren't too many.

Regarding the tentative solution, wouldn't it be redundant to have 2 functions that pass the request parameters? I like the first solution that allows the anchor to save the transaction and link it to the rest of the data model in the same function as processing the request fields.

**Comment by JakeUrban** [comment]
I also could release a version prior to 1.0 with the changes discussed here.

**Comment by yuriescl** [comment]
@JakeUrban For SEP-6 deposits, if the Anchor wants to return some kind of external memo or note to be used in the external transaction, this feature is required as well, since the Anchor has to link the external transaction to the initial SEP-6 transaction.
For example, a SEP-6 `/deposit` response:
```
{
    "min_amount": 10.0,
    "max_amount": 10000.0,
    "how": "Send a SEPA transfer to our bank account with note TX1234",
    "fee_fixed": 1.0,
    "fee_percent": 2.0,
    "extra_info": {
        "message": "Send a SEPA transfer to our bank account with note TX1234"
    }
}
```

In this case I'd have to associate `TX1234` with the `Transaction` so I could identify the incoming deposit later.

**Comment by yuriescl** [comment]
Also, maybe it's a good idea to add an optional `id` field to the response so the Wallet can track the transaction:
```
{
    "id": "12345678",
    "min_amount": 10.0,
    "max_amount": 10000.0,
    "how": "Send a SEPA transfer to our bank account with note TX1234",
    "fee_fixed": 1.0,
    "fee_percent": 2.0,
    "extra_info": {
        "message": "Send a SEPA transfer to our bank account with note TX1234"
    }
}
```
https://github.com/stellar/stellar-protocol/issues/615

**Comment by JakeUrban** [comment]
We'll release a solution in 0.13. While I think `id` should've been added to the SEP-6 standard I don't think its required. The wallet can use its own identifier for its transaction tracking.

**Comment by yuriescl** [comment]
@JakeUrban Thanks a lot!
