### ISSUE TITLE
Feature Request: get settings from settings.py if not in .env

### ISSUE THREAD

**Issue by yuriescl** [stellar/django-polaris#248]
Polaris currently requires the Django app to create a `.env` file and put the Polaris settings there.
But Django settings are usually placed in `settings.py`, possibly overriden in a `local_settings.py`.
If the developer wants to get the settings from the environment (`.env` or environment variables), he should have the option to do so, but that should not be enforced like it currently is by Polaris.

My suggestion is to either remove the need for a `.env` file, or make it optional to get the settings from the environment and maybe control that option through a flag in `settings.py`, something like `POLARIS_ENV`.

The main reason for asking this is because I'd like to have all settings on `settings.py`, with local settings in `local_settings.py`, this way I can avoid multiple settings files (.json, .yaml, etc).
Celery for example reads settings from `settings.py` by default, with the prefix `CELERY_`.
So Polaris could have something like:
```
# settings.py

POLARIS_STELLAR_NETWORK_PASSPHRASE = ""
POLARIS_SIGNING_SEED = ""
```

**Comment by yuriescl** [comment]
Also, it's strange that currently some settings are required to be in `settings.py` and others in `.env`.
Currently these settings are required by Polaris in `settings.py`:
```
ACTIVE_SEPS = ['sep-6', 'sep-10']
SECURE_SSL_REDIRECT = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
```
If some settings can be in `settings.py`, why not all settings?
```
POLARIS_STELLAR_NETWORK_PASSPHRASE = ""
POLARIS_SIGNING_SEED = ""
...
POLARIS_ACTIVE_SEPS = ['sep-6', 'sep-10']

SECURE_SSL_REDIRECT = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
```

**Comment by JakeUrban** [comment]
Before I address the issue, I actually really like the idea of prepending polaris-specific settings in `settings.py` with `POLARIS_`. I think I'll add that for the next release.

Some settings are provided by Django, like `SECURE_SSL_REDIRECT` or `SECRET_KEY`. All Django settings should be in `settings.py`. If the setting should be kept secure though, it should probably specified in the environment and read into `settings.py`. So `SECRET_KEY`, for example, should be specified in `settings.py` like so:
```
SECRET_KEY = env("SECRET_KEY").  # env is an environment object
```
At the very minimum, your code should be private if you have secret settings directly in your code.

Polaris then has polaris-specific settings unrelated to Django. Check out [this file](https://github.com/stellar/django-polaris/blob/master/polaris/polaris/settings.py) to see how Polaris uses environment variables and how it stores non-django settings.

But to answer your question, in general, the environment settings (those in `.env`) are for three different kinds of attributes:
- Those that must be kept secret (not checked into git, more on this later)
- Those that change depending on local/production deployment
- Those that change depending on testnet/mainnet deployment

So `STELLAR_NETWORK_PASSPHRASE` should be specified in the `.env` because _you shouldn't have to change the code for it to work a new/different environment or network_. If you had this setting in `settings.py`, you'd have to change it when deploying to mainnet. `SIGNING_SEED`, `HORIZON_URI`, and `HOST_URL` all also work like `STELLAR_NETWORK_PASSPHRASE`. 

Conversely, `ACTIVE_SEPS` is in `settings.py` because the SEPs you want out of Polaris doesn't change when you change environments or networks. This is actually the only setting in `settings.py` that isn't related to Django but is still in the `settings.py` file.

However, `SERVER_JWT_KEY` _could_ be directly in `settings.py` if your code was private, even though it really shouldn't be due to security concerns. 

I can change Polaris to look for all these settings in the environment first but resort to the `settings.py` file if they aren't present, but environment variables are a very standard way to handle these types of settings and I encourage you to use them. If you want to be able to specify everything in `settings.py` and change your change for different environments I can change Polaris to look in `settings.py` after looking in the environment.

**Comment by yuriescl** [comment]
@JakeUrban I agree with all the points, and my `settings.py` don't change, what changes is `local_settings.py`, which is in `.gitignore` just like `.env`.
I do see the reasoning behind using `.env`, but on my case I tend to keep everything in Python including the settings, that's why I put everything on `local_settings.py`.
My suggestion for Polaris is to remove the requirement for the `.env` and allow the developer to choose where to put the settings (`.env` or `settings.py` - whatever fits best).

> I can change Polaris to look for all these settings in the environment first but resort to the settings.py file if they aren't present

That'd be great :)

**Comment by JakeUrban** [comment]
@yuriescl I see, so really your `local_settings.py` serves the same purpose as `.env` except its a python file. Does everything in `local_settings.py` get imported into `settings.py`?

**Comment by yuriescl** [comment]
> I see, so really your local_settings.py serves the same purpose as .env except its a python file

Yes, the main reason for that are dictionaries and lists, I can write them directly in Python

> Does everything in local_settings.py get imported into settings.py?

Yes:
```
# settings.py
try:
    from .local_settings import *
except ImportError:
    print('Failed to import local settings')
