### ISSUE TITLE
Adjust documentation on amount_in

### ISSUE THREAD

**Issue by yuriescl** [stellar/django-polaris#251]
In [here](https://github.com/stellar/django-polaris/blob/master/polaris/polaris/integrations/rails.py#L37) it says _If the amount differs from the original amount but is still valid, do not forget to recalculate amount_fee_, but I'm not sure how to compare the value of `amount_in` with its previous value (from initial SEP-6/SEP-24 call), because the value gets overwritten before `execute_outgoing_transaction` is called.

**Comment by JakeUrban** [comment]
If `amount_in` is valid and you have the info needed to facilitate the transfer, it doesn't really matter what the previous `amount_in` was. I can adjust the phrasing of the documentation.

It gets tricky when you no longer have enough information but the amount is still valid. Lets say you need more KYC info when the amount is larger than 1K but the user originally specified 100. If you can get the user to update the info outside the typical interactive flow (since thats already happened), then you can support the entirety of the larger amount. 

If you can't get the user to update their info, then you would have to refund the user. You can do this partially or entirely.

**Comment by JakeUrban** [comment]
Do you think its actually a functional problem that we don't have the initial `amount_in` within `execute_outgoing_transaction()`?

**Comment by yuriescl** [comment]
@JakeUrban This issue was more like a question than a bug report, the documentation made it sound there was a way to compare (the value was saved somewhere), but I agree, the previous value of `amount_in` is not relevant once the user sends the payment.

> Do you think its actually a functional problem that we don't have the initial amount_in within execute_outgoing_transaction()?

No.

> I can adjust the phrasing of the documentation.

I think that's the only change needed for this issue. Maybe remove the part where it mentions comparing the values (since it's not possible atm).

**Comment by JakeUrban** [comment]
The new explaination:

> When this function is called, ``transaction.amount_in`` is the amount sent to the anchor, `not the amount specified in a SEP-24 or SEP-31 API call`. This matters because the amount actually sent to the anchor may differ from the amount specified in an API call. That is why you should always validate ``transaction.amount_in`` and calculate ``transaction.amount_fee`` here.
