### ISSUE TITLE
Feature Request: Serve Static TOML File

### ISSUE THREAD

**Issue by jcooter** [stellar/django-polaris#284]
**What problem does your feature solve?**
Adding other SEP-1 token metadata to the Asset object will allow for more robust sep-1 generation, as well as allowing metadata to be used by other django apps and business logic

**What would you like to see?**
SEP-1 defines informational metadata for tokens (e.g. name, image, asset type, etc.). It would be nice to have this information included in the Asset model.

**What alternatives are there?**
Currently, the alternative is to define this manually in a SEP-1 integration (which does not allow other apps to take advantage of the information), or to create a separate db model to contain the metadata with a one-to-one mapping to an Asset (which asks for the user to duplicate boilerplate work)

**Comment by JakeUrban** [comment]
Hi @jcooter, when you say meta data, do you mean this part of SEP-1?
```
# asset with meta info
[[CURRENCIES]]
code="GOAT"
issuer="GD5T6IPRNCKFOHQWT264YPKOZAWUMMZOLZBJ6BNQMUGPWGRLBK3U7ZNP"
display_decimals=2
name="goat share"
desc="1 GOAT token entitles you to a share of revenue from Elkins Goat Farm."
conditions="There will only ever be 10,000 GOAT tokens in existence. We will distribute the revenue share annually on Jan. 15th"
image="https://static.thenounproject.com/png/2292360-200.png"
fixed_number=10000
```
So you'd like the `Asset` model to have `name`, `desc`, `conditions`, etc. ?

**Comment by jcooter** [comment]
Yep, that's what I'm looking for.  I implemented this in a branch off the 0.13.1 release because master was broken at the time.  I can try to put together a PR this weekend.

**Comment by JakeUrban** [comment]
The only hesitation I have is that I intended to squash the migration files used to modify Polaris' DB schema for the 1.0 release, with the assumption that no schema changes would happen between 0.13.1 and 1.0. Can this functionality be slated for a 1.1 release?

**Comment by JakeUrban** [comment]
In the meantime, we should merge your PR into a 1.1 branch

**Comment by jcooter** [comment]
Yeah, that's fine.  I'm using this for a hobby project of mine, so I don't have any pressing need.

**Comment by JakeUrban** [comment]
Hey Joe,

I'm looking at the SEP-1 CURRENCY attribute definitions and I'm beginning to feel as if having a column for each attribute is overkill. Some of these will rarely ever be used, and others may appear to be significant to Polaris but are not, like `status`.

I would suggest defining a Python object, Django model, dict, or module for the SEP-1 attributes you'd like to use in the TOML file but are not on the `Asset` object, and import those attributes wherever you need to use them for other application logic.

If you defined an `AssetExtra` model for example, you could also add an FK to `Asset`, and load both when querying in your application logic.

Let me know your thoughts.

**Comment by yuriescl** [comment]
This feature does make sense at some point, but storing `.toml` info in the database only for the Asset wouldn't make sense to me because there are too many fields in SEP-1 that are not used by Polaris, and it would fill the model with unused fields.
For the Anchor I suggest:
1) Have a static `.toml` file which is served directly by your webserver, which makes is easily cacheable and its all you need for SEP-1.
2) If you need to read info from the `.toml`, either read from the file directly (`with open(toml)...`) or fetch it using something like `requests.get(toml)`, and since it's probably in the same server and possibly cached, it will be very fast to fetch it.
3) If you really need the info in the database, create an `AssetExtra` model with a `OneToOneField` relation to Polaris `Asset` model. All you need is `asset.extra.<your field>` to access it.

@JakeUrban If more Anchors request this I imagine it might be worth reconsidering.

**Comment by JakeUrban** [comment]
I think thats definitely the way to go. We can follow the same approach we used with JS script integrations and deprecate the current TOML function while adding support for rendering a static TOML file.

**Comment by JakeUrban** [comment]
@jcooter how does this sound? You would still have to import and parse a TOML file but you could keep this in memory after the first read and access it throughout the application.

**Comment by yuriescl** [comment]
> I think thats definitely the way to go. We can follow the same approach we used with JS script integrations and deprecate the current TOML function while adding support for rendering a static TOML file.

If by render you mean return the TOML string from the integration function, I agree. It's up to the Anchor how to cache it.

**Comment by JakeUrban** [comment]
The TOML integration returns a dictionary that is passed to a `toml` python library that generates a TOML-formatted string rendered to the client.

If the function is implemented, we'll use it. Otherwise, Polaris will look for a `stellar.toml` template file in in the app's `templates` directory. Polaris might provide a default TOML, so the path might be `templates/polaris/stellar.toml`.

**Comment by JakeUrban** [comment]
I've realized the approach outlined above imposes limitations that don't exist with the current integration function. 

Specifically, the anchor would be required to specify the data directly in the template instead of querying their DB and returning content to be rendered by their template code. This is because this template rendering flow doesn't include the `content_for_template()` call that is made for the other templates.

Instead, we have the registered TOML function, which exists today. So instead of deprecating and removing the registered TOML function, we're going to _augment_ the functionality offered by allowing users of Polaris to extend or override the `polair/stellar.toml` template thats used to render the content (`context`) returned from the registered TOML function.

**Comment by JakeUrban** [comment]
So now that I've implemented some of this I'm beginning to question if this actually helps. From my experience, the anchor can do everything I'm doing with the `stellar.toml` template with the current TOML integration function, having a `stellar.toml` base template doesn't help. Furthermore, writing a TOML file that accepts variables is tedious.

Here is what the base template looks like:
```
ACCOUNTS = [{% for account in ACCOUNTS %}
    "{{account}},"
{% endfor %}]
VERSION = "{{VERSION}}"
SIGNING_KEY = "{{SIGNING_KEY}}"
NETWORK_PASSPHRASE = "{{NETWORK_PASSPHRASE}}"
{% if TRANSFER_SERVER %}TRANSFER_SERVER = "{{TRANSFER_SERVER}}"{% endif %}
{% if TRANSFER_SERVER_SEP0024 %}TRANSFER_SERVER_SEP0024 = "{{TRANSFER_SERVER_SEP0024}}"{% endif %}
{% if WEB_AUTH_ENDPOINT %}WEB_AUTH_ENDPOINT = "{{WEB_AUTH_ENDPOINT}}"{% endif %}
{% if KYC_SERVER %}KYC_SERVER = "{{KYC_SERVER}}"{% endif %}
{% if DIRECT_PAYMENT_SERVER %}DIRECT_PAYMENT_SERVER = "{{DIRECT_PAYMENT_SERVER}}"{% endif %}
```

Here is what the example server's extension would look like:
```
{% extends "polaris.stellar.toml" %}

{% if CURRENCIES %}{% for c in CURRENCIES %}
[[CURRENCIES]]
code = "{{c.code}}"{% endif %}
code_template = "{{c.code}}"{% endif %}
issuer= "{{c.issuer}}"{% endif %}
status= "{{c.status}}"{% endif %}
display_decimals = "{{c.display_decimals}}"{% endif %}
{% endfor %}]{% endif %}
```

Why would an anchor prefer to define their TOML this was as opposed to autogenerating the file from a dictionary that you need to use for the new feature anyway? Using TOML templates just seems to add more work for anchors.

**Comment by JakeUrban** [comment]
The only way I see this being less work is if the anchor can just define a static TOML file with no variables instead of Polaris calling the TOML integration function and rendering a template that uses those variables.

I think this is a reasonable tradeoff. If you want to use the `stellar.toml` template, you have to define one statically, meaning it accepts no variables because `registered_toml_func()` won't be called if implemented.
