### ISSUE TITLE
SEP-24: `withdraw_memo` not populated when `Transaction.status` is `pending_user_transfer_start`

### ISSUE THREAD

**Issue by yuriescl** [stellar/django-polaris#291]
This happens with withdrawals:
The `watch_transactions` command is not changing the status to `pending_anchor` for transactions that occur when `watch_transaction` is not running.

**Expected behavior:**  
When the `watch_transaction` command starts, it should recognize payments made before it was running and change their status to `pending_anchor`.

**Current behavior:**  
`watch_transactions` is only changing status to `pending_anchor` for transactions that occur when `watch_transactions` is running.

**How to reproduce:**
- Delete the database
- Migrate
- Create the asset
- Run the server (`manage.py runserver`)
- Create a SEP-6 withdrawal
- Make the Stellar payment to the anchor account with the hash memo
- Start `watch_transactions` and wait around 30 seconds
- Stop `watch_transactions`
- Check the transaction status and it's still `pending_user_transfer_start`

When `watch_transactions` is running and the stellar payment is made, the status is correctly set to `pending_anchor`.

**Comment by JakeUrban** [comment]
I'm able to make a SEP-6 withdraw request that ends with `completed` using the SEP-6 [demo client](http://sep6-demo.netlify.com/#HOME_DOMAIN=%22https://testanchor.stellar.org%22&TRANSFER_SERVER=%22%22&WEB_AUTH_ENDPOINT=%22%22&USER_SK=%22SB3ADKIHLQ7Y6I6UUPWCZVUE3GFCHGC2UGRXI6Y5CO7PPVV7WNCGNAEK%22&HORIZON_URL=%22https://horizon-testnet.stellar.org%22&ASSET_CODE=%22SRT%22&ASSET_ISSUER=%22%22&EMAIL_ADDRESS=%22%22&STRICT_MODE=true&AUTO_ADVANCE=true&PUBNET=false)

**Comment by JakeUrban** [comment]
Let me turn off the `watch_transactions` process on our reference server and see if it works when I turn it back on.

**Comment by JakeUrban** [comment]
I tested this multiple times, and `watch_transactions` seems to successfully detect transactions that happened while the process was down.

**Comment by JakeUrban** [comment]
@yuriescl I don't want to release 0.13.2 if I'm wrong, so let me know if I can help resolve this issue.

`watch_transactions` uses the latest withdrawal `Transaction` object's `paging_token` value to start streaming. So if you're testing the service with an empty database without `watch_transactions` running, its not going to pick up the transaction since Polaris doesn't know where to start. If there are no completed withdrawal transactions in the DB, Polaris will stream with `"now"`.

In this case, Polaris _could_ try to be smart and query for the earliest `Transaction` object's `started_at` timestamp, convert that to a unix timestamp, and use that as the streaming cursor.

However, I think the empty-database case is rare. If you're just starting Polaris, you should be running `watch_transactions`. If you've streamed transactions before, `watch_transactions` will always pick up incoming transactions.

**Comment by JakeUrban** [comment]
[0.13.2](https://github.com/stellar/django-polaris/releases/tag/v0.13.2) has been released.

**Comment by ianeinser** [comment]
I am sorry but I need to reopen this issue again.

I encounter the same bug when running the master repo.

This happens with withdrawals:
The watch_transactions command is not changing the status from pending_user_transfer_start to pending_anchor for transactions that occur when watch_transaction is not running.

I am using the master repo of stellar-demo-wallet. The withdrawal transaction is submitted by the wallet but the watch_transactions stays idle and the wallet keeps sending GET /sep24/transaction?id=3eb0584c-4d21-461c-930a-157c6508f527 HTTP/1.1" 200 667 and receving pending_user_transfer_start.

I am using the example folder of the master repo

**Comment by JakeUrban** [comment]
@ianeinser you probably need to run `python manage.py testnet reset`. Polaris starts streaming from the last completed transaction's `paging_token`. When testnet resets, Horizon's paging tokens reset. Running `testnet reset` ensures the next invocation of `watch_transactions` uses a streaming cursor value of `now`.

**Comment by ianeinser** [comment]
> @ianeinser you probably need to run `python manage.py testnet reset`. Polaris starts streaming from the last completed transaction's `paging_token`. When testnet resets, Horizon's paging tokens reset. This means `watch_transactions` uses an invalid paging token after the reset. Running `testnet reset` ensures the next invocation of `watch_transactions` begins streaming transactions from the beginning of the account's history.

Hi Jake,

thanks. I just found out that watch_transactions works but get stucked due to empty memo. I checked when using stellar-demo-wallet and found out that memo is null whilst memo_type is hash. Hence i added these lines in def after_form_validation of integrations.py 

# generate memo using transaction id
            transaction_id_hex = transaction.id.hex
            padded_hex_memo = "0" * \
                (64 - len(transaction_id_hex)) + transaction_id_hex
            transaction.memo = memo_hex_to_base64(padded_hex_memo)

            transaction.save()

And it works now.

i also checked /polaris/sep24/withdraw.py and found out that memo should be automatically generated using transaction id and added when interactive flow is complete. When i checked the db, the memo is null/empty.  I am not sure why the memo cannot be generated.

**Comment by JakeUrban** [comment]
Hi @ianeinser,

I just tried performing a SEP-24 withdraw with the demo wallet and confirmed your experience, `withdraw_memo` is `null` when the transaction's `status` is `pending_user_transfer_start`. I'm not sure why the memo wouldn't be saved to the DB since the change and the status change is made with the same INSERT statement [here](https://github.com/stellar/django-polaris/blob/master/polaris/polaris/sep24/withdraw.py#L161).

I'll look into this a bit more, thanks for reporting.

**Comment by JakeUrban** [comment]
The bug was introduced in an unreleased [commit](https://github.com/stellar/django-polaris/commit/51054073784914ba4ffc843dff4f7b9ed8081984). Polaris assigns the `memo` field directly before refreshing the transaction object in memory [here](https://github.com/stellar/django-polaris/commit/51054073784914ba4ffc843dff4f7b9ed8081984#diff-c4ffcd7249fa60705223da98d1dfe43ad75eb2848bfbb0b372e53b8677d36043R154-R156).

A quick fix would be to refresh the transaction prior to assigning the `memo` value.
