### ISSUE TITLE
amount_fee not set during SEP-24 flow

### ISSUE THREAD

**Issue by yuriescl** [stellar/django-polaris#427]
Is there a reason Polaris doesn't set `Transaction.amount_fee` automatically during SEP-24 flow (
https://github.com/stellar/django-polaris/blob/master/polaris/polaris/sep24/deposit.py#L127), but does set it in `poll_pending_deposits` (https://github.com/stellar/django-polaris/blob/master/polaris/polaris/management/commands/poll_pending_deposits.py#L164)?

SEP-24 Fee field will display `None` until the deposit is executed:

![image](https://user-images.githubusercontent.com/26092447/119704368-f2213380-be2d-11eb-9890-beaae50da426.png)

But it does display the fee when filling the amount:
![image](https://user-images.githubusercontent.com/26092447/119701912-41199980-be2b-11eb-8ef0-fc1e7bcd3deb.png)

**Comment by JakeUrban** [comment]
The original idea was to not display a fee until the funds were delivered to the user. However I think we match the behavior of the `amount_in` field, which has a "To Be Received" label prior to the anchor receiving funds. We can do the same for "Amount Deposited" --> "Amount To Be Deposited".

**Comment by yuriescl** [comment]
> We can do the same for "Amount Deposited" --> "Amount To Be Deposited"

I agree

About `amount_fee`, I think it could be initialized in the same places as `amount_in`. The anchor usually has to handle `amount_in` and `amount_fee` anyway in the rails code, so having an `amount_fee` there already wouldn't make much difference.

**Comment by JakeUrban** [comment]
After thinking about this some more I'm realizing that the SEPs don't clarify whether or not `amount_fee` and `amount_out` can or should be non-null before the transaction is completed. Right now, Polaris doesn't populate `amount_fee` or `amount_out` until the transaction is complete.

It is possible that a client application checks `amount_out` to determine if funds have been delivered, but I'm not sure how common that practice is. `status` is the source of truth for the state of the transaction, and clients _should_ be using this attribute instead of `amount_out`.

I think we should clarify in the SEPs that `amount_in`, `amount_fee`, and `amount_out` can (and probably should) be assigned a value as soon as the values can be calculated. In the same change we should reiterate that `status` is the attribute that communicates whether or not funds have been received by the anchor and delivered to the user.

I'll make the change in Polaris now but won't release it until the clarifications to the SEPs have been merged.

**Comment by JakeUrban** [comment]
@yuriescl I'm thinking about only calculating `amount_fee` and `amount_out` automatically if the anchor didn't register a custom fee function, meaning `fee_fixed` and `fee_percent` are used instead.

This is because Polaris currently only calls the registered fee function when a request to `/fee` is made, and if it began calling the function as soon as `amount_in` was provided, it wouldn't provide a `type` parameter. If the anchor requires the `type` parameter in the endpoint,  the anchor wouldn't be able to calculate the fee if Polaris called the function outside a `/fee` request.

I think this should be fine because the anchor could always assign values to `Transaction.amount_fee` and `Transaction.amount_out` in the `DepositIntegration.after_form_validation()` or `DepositIntegration.after_form_validation()` functions once `amount_in` was collected via a transaction form. In SEP-6, the anchor could use the optional `amount` parameter value sent in `/deposit` or `/withdraw` requests.

Let me know what you think.

**Comment by JakeUrban** [comment]
The use of `TransactionForm` is disjoint from the use of `registered_info_func`, since the former is only used in SEP-24 and the latter is only used in SEP-6. As pointed out in stellar/stellar-protocol#614, SEP-24's `/info` doesn't define `type` values like SEP-6 does, so currently it wouldn't make sense for SEP-24's `TransactionForm` to extract the `type` values from SEP-6's `registered_info_func`. 

In general, I'm not convinced that `type` parameters are the best mechanism for accounting for the variation in fee calculation, but thats a conversation for a later date.

As it stands today, Polaris anchors can use the integration functions provided by SEP-24 (`after_form_validation()`) and SEP-6 (`process_sep6_request()`) to populate `amount_fee` and `amount_out` as soon as the client provides the amount via a `TransactionForm` or `amount` parameter respectively. I did exactly this for testanchors.stellar.org in #429. And if SEP-24 anchors require a `type`-like parameter to calculate fees, they can add a field to their `TransactionForm`.

**Comment by yuriescl** [comment]
You're right, I completely forgot the fact that /info defines types for SEP-6 only. It doesn't make sense to use it for SEP-24.
But I do think there should be a mechanism to pass a type value when Polaris calls /fee in the interactive flow, since Anchors can have different fees for each transfer type. And the fee displayed in the form does depend on the transfer type selected by the user.
For a example, a credit card deposit can have a different fees than a bank transfer deposit.
I'm still not clear about calculate_fee and where/how Polaris should call it, because like I said, the return value can depend on type, and I feel that it can be confusing to register a custom calculate_fee but also have to call it manually inside an integration function.
If Polaris is collecting the amount, and Polaris provides a fee integration function, then Polaris should calculate the fee as well.

**Comment by yuriescl** [comment]
In my case I'm subclassing TransactionForm and adding a dropdown for the transfer type, but Polaris is not using the type value from the dropdown when calling /fee, therefore it's displaying an incorrect fee.

**Comment by JakeUrban** [comment]
We can standardize the `type` form field's name so that `base.html`'s JavaScript can use it in requests to the `/fee` endpoint. We already do this with the `TransactionForm.amount` field. Do you think `TransactionForm.transaction_type` make sense? I feel like `TransactionForm.type` could work too, but its a bit generic and anchors could already be using it.

**Comment by yuriescl** [comment]
I'd look for a Django `type` form field, which would have id `id_type` by default in the HTML:
```
const typeField = document.getElementById('id_type');
if (typeField) {
    params.append("type", typeField.value);
}
```
Then the Anchor could add a type field if they want Polaris to use it:
```
class MyDepositForm(TransactionForm):
    type = forms.TypedChoiceField(
        label=_('Type'),
        help_text=_('Deposit transfer type'),
        choices=[('bank_account', _('Bank account')), ('credit_card', _('Credit card'))]
    )

    field_order = ['type', 'amount']
```

This can be a breaking change if Anchors already have a `id_type` with another purpose, but I couldn't think of a simpler way of adding type support.

`transaction_type` and `transfer_type` are also good candidates for the field name.

**Comment by JakeUrban** [comment]
I took some time to think through how Polaris could be calculate fees for the anchor, and came up with the following:

### SEP-24

With change changes made in #432, all we would need to do is call the registered fee function after a `TransactionForm` has been submitted for a deposit or withdraw request.

### SEP-6

`GET /withdraw` requests require a `type` parameter. This means we can validate and use it in a call to the registered fee function prior to calling `WithdrawalIntegration.process_sep6_request()` _if the `amount` parameter is also passed_. If `amount is not passed we will obviously not calculate the fee.

`GET /deposit` does not require a `type` parameter. If both `amount` and `type` are passed, we will call the fee calculation function. If `amount` is passed without `type` and `type` is listed as required in `/info`, we will return a 400 response. If only `amount` is passed and `type` is not required, we will still call the fee calculation function.

### Poll Pending Deposits

Polaris cannot calculate the transaction fee here because Polaris doesn't know the `type` of the transaction.

### Watch Transactions

Polaris also cannot calculate the fee here for the same reason.

**Comment by JakeUrban** [comment]
I'm putting this in my "done" column for internal tracking but I can make the changes outlined above in a later sprint.

**Comment by yuriescl** [comment]
Sure, thanks for the changes :D

**Comment by JakeUrban** [comment]
I'll be implementing changes mentioned in the SEP-24 section of my [earlier comment](https://github.com/stellar/django-polaris/issues/427#issuecomment-852471639) within the context of #452

**Comment by JakeUrban** [comment]
I'm going to close this issue because the logic required for calculating fees in SEP-6 flows is fairly nuanced and will likely just confuse the developer. It is simpler for the anchor to understand that fees must be added to the expected amount sent in their own integration functions.
