### ISSUE TITLE
more_info txJSON parse error

### ISSUE THREAD

**Issue by yuriescl** [stellar/django-polaris#448]
It seems `postMessage` JavaScript callback is not working in SEP-24.
I've tested by creating a deposit and opening a popup manually:
```javascript
window.addEventListener("message", (event) => {
  print(event)
}, false);
url = getInteractiveUrl()
p = window.open(url, 'popup', 'width=500,height=800')
```

I completed the SEP-24 flow but didn't get a callback.
Is there a way to test `postMessage`? The Demo Wallet apparently uses a poll mechanism instead of listening to the callback.

**Comment by yuriescl** [comment]
I'm debugging this a bit more, maybe the issue is not on Polaris.

**Comment by yuriescl** [comment]
It's failing to parse the transaction JSON string it it contains a `\n`:

![image](https://user-images.githubusercontent.com/26092447/125618111-abc0c7a6-bf23-46b7-80f7-b1198ccfa861.png)

![image](https://user-images.githubusercontent.com/26092447/125618194-72bb0b94-28c1-4783-a99b-e0ee2c582e5c.png)

**Comment by yuriescl** [comment]
Is that an expected error? Should avoid using `\n` inside the transaction fields?

**Comment by JakeUrban** [comment]
The issue is the way JavaScript handles strings and special characters:

![Screen Shot 2021-07-19 at 2 54 18 PM](https://user-images.githubusercontent.com/10968980/126232328-26c2ac86-6994-4900-83c4-0e91c017f50e.png)

But if you specify that the special `\n` character should be escaped it works:

![Screen Shot 2021-07-19 at 2 54 53 PM](https://user-images.githubusercontent.com/10968980/126232384-9ec7fd1d-6ea3-4156-b7d2-0e3edcd05396.png)

**Comment by yuriescl** [comment]
I guess I'll have to replace `\n` with `\\n` in Python before passing the string to the template. Thanks.
