### ISSUE TITLE
Questions about pending trust and non-existing accounts

### ISSUE THREAD

**Issue by yuriescl** [stellar/django-polaris#456]
Hi, I've looked into Polaris code to find how it handles deposits for accounts that have no trustline to the Anchor.
Just to confirm, is this correct?
- If the destination Stellar account does not exist, Polaris creates it and funds it with enough XLM to create the trust to the Anchor, then Polaris sets the status as `pending_trust`
- If the destination Stellar account does exist, but has no trustline to the Anchor, Polaris checks if claimable balance is supported. If yes, it creates a claimable balance for the deposit. If not, it doesn't do anything and just sets the transaction status as `pending_trust`

It seems like Polaris doesn't fund existing accounts which don't have a trustline. Is there a reason for that?

**Comment by JakeUrban** [comment]
Thats mostly correct. If a Stellar account doesn't exist Polaris creates it and will immediately send a claimable balance if the wallet sends the `claimable_balance_supported: true` parameter in the deposit request. A transaction only goes to `pending_trust` if `claimable_balance_supported` is `false` or was not sent.

> It seems like Polaris doesn't fund existing accounts which don't have a trustline. Is there a reason for that?

The only reason is because it is a rare case. If an account exists, it almost certainly has enough XLM that can be used for the reserve of a new trustline to the anchor's asset. We could add functionality to detect if this is not the case and make a payment operation with the XLM required for a new trustline.

If my assumption is incorrect and this is a common occurrence then we can add this functionality.

**Comment by yuriescl** [comment]
Maybe Polaris could have a setting to enable funding accounts (existing or non-existing).

As pointed by @antb123, anchors might lose money if they get spammed with low amount deposits for non-existing accounts (Polaris would fund too many accounts and spend too much XLM doing that).

**Comment by JakeUrban** [comment]
Thats true, although the anchor can protect against that by charging a larger fee if the account doesn't exist or is underfunded.

There has been discussion around adding such a flag though. The issue here is that there is no standardized way to signal to the wallet that the anchor doesn't support funding accounts. This would require a flag on the anchor's `/info` endpoint, which I've added an [issue](https://github.com/stellar/stellar-protocol/issues/1030) for.

**Comment by antb123** [comment]
The main issue would be if for example someone deposits 0.10 cents of crypto - but funding the account costs 1.5 XLM (0.40 cents). They could in theory drain all the Anchors XLM

**Comment by yuriescl** [comment]
> Thats true, although the anchor can protect against that by charging a larger fee if the account doesn't exist or is underfunded.
> 
> There has been discussion around adding such a flag though. The issue here is that there is no standardized way to signal to the wallet that the anchor doesn't support funding accounts. This would require a flag on the anchor's `/info` endpoint, which I've added an [issue](https://github.com/stellar/stellar-protocol/issues/1030) for.

Seems like this was implemented, thanks a lot!
