### ISSUE TITLE
Database is locked errors

### ISSUE THREAD

**Issue by yuriescl** [stellar/django-polaris#466]
I'm using SQLite in a test server and I'm getting many `Database is locked` errors. This is caused when running `poll_pending_deposits` and trying to save changes to the polaris transactions inside the integration function.
From looking at Polaris code I see that it uses `atomic` and locks the transactions.

Do you usually get those database lock errors? Should I avoid saving a Polaris transaction (`transaction.save()`) inside an integration function?
Maybe this is some kind of deadlock issue being caused by my changes to the models inside the integration functions.

Another question, which method do you recommend for cleaning up `incomplete` and `pending_user_transfer_start` transactions? I have a management command that filters transactions older than certain days and just deletes them. The issue is that this can happen at the same time that Polaris is polling the same transactions. How to avoid that?

**Comment by JakeUrban** [comment]
I have not gotten `Data is locked` errors when running SQLite3, are you using version 3? SQLite3 doesn't support `SELECT ... FOR UPDATE` -- it is treated as a simple `SELECT` statement. I recommend the following:

1. Stop all processes
2. Make a copy of the database file
3. Overwrite the original database file with the copy
4. Add the Django DEBUG-level logger which outputs all queries made to the DB
5. Start all processes

If the problem is related to your code, you'll get the `Database is locked` error again but you'll be able to see the sequence of queries made to arrive at that state.

It is required that any changes made to a transaction are `save()`'ed before returning from `poll_pending_deposits()`.

**Comment by JakeUrban** [comment]
Hi @yuriescl, are you still having deadlock issues?

**Comment by yuriescl** [comment]
I haven't tested much yet, but I'm closing this and will re-open with more details if it happens again. Thanks a lot for the tips and suggestions.
